### ISSUE TITLE
NullReferenceException: On dictionary in DefaultStorageStrategy

### ISSUE THREAD

**Issue by amorel** [Mangopay/mangopay2-net-sdk#103]
Here's the Stacktrace:

```
at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
at MangoPay.SDK.Core.DefaultStorageStrategy.Store(OAuthTokenDTO token, String envKey)
at MangoPay.SDK.Core.AuthorizationTokenManager.GetToken()
at MangoPay.SDK.Core.AuthenticationHelper.GetHttpHeaderStrong()
at MangoPay.SDK.Core.RestTool.GetHttpHeaders(String restUrl)
at MangoPay.SDK.Core.RestTool.DoRequest[U,T](String idempotencyKey, String urlMethod, Pagination pagination, T entity)
at MangoPay.SDK.Core.RestTool.Request[U,T](ApiEndPoint endPoint)
```

I included the SDK in my solution but I found no value in Null!
By doing some research, I found that the error sometimes happened with concurrent accesses!

I had to change Dictionary to ConcurrentDictionary !

**Comment by amorel** [comment]
@SoloJr 
What I have in my "Startup.cs" :

services.AddSingleton<IMangoPayAPIService, MangoPayAPIService>();
services.AddScoped<IMangoPayService, MangoPayService>();

In MangoPayAPIService, I get my "new MangoPayApi()" (initializied in constructor) object with settings ClientId, ClientPassword, BaseUrl...
And in my MangoPayService, this is my use of MangoPay api...

If my memories are good, I had the problem when I started the project from Visual Studio but the exception is not raised every time !
I can no longer reproduce the problem now but when I changed Dictionary into ConcurrentDictionary, I no longer had the problem...

**Comment by amorel** [comment]
I've had the following error again when I use a "Dictionary":

![image](https://user-images.githubusercontent.com/2759186/87930906-28ad5580-ca89-11ea-91b4-70c7d761f90b.png)

  at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.ContainsKey(TKey key)
   at MangoPay.SDK.Core.DefaultStorageStrategy.Store(OAuthTokenDTO token, String envKey) in **project_path**\MangoPay.SDK\Core\DefaultStorageStrategy.cs:line 28
