### ISSUE TITLE
Not compatible with RestSharp 110.2.0

### ISSUE THREAD

**Issue by feradz** [Mangopay/mangopay2-net-sdk#204]
mangopay2-sdk 3.12.2 throws a runtime exception/error when trying to call any API method.

For example, when I call `PayOutDTO payOutResult = await _mangoPayApi.PayOuts.CreateBankWireAsync(payOut);`

`public async Task CreateBankWireAsync(PayOutBankWirePostDTO payOut, string idempotentKey = null)`

```
One or more errors occurred. (Method not found: 'Void RestSharp.RestClientOptions.set_Timeout(Int32)'.)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
```

This error occurs because you are not targeting the latest version of RestSharp 110.2.0. 110.2.0 has breaking changes with older versions specifically RestSharp 108.0.3 which your library works with. 

Please, resolve this issue ASAP because right now our integration is broken.

**Comment by feradz** [comment]
Any update on this issue?

**Comment by xps** [comment]
I have no opinion whether MangoPay should update to the latest version of RestSharp (many of us are probably still using the older versions, and the update may break other dependencies...), but there are ways to use 2 different versions of RestSharp in the same project.

**Comment by iulian03** [comment]
Hi @feradz 

Currently the library uses RestSharp version 112.1.0
We hope this fixes your issues.
