### ISSUE TITLE
NullReferenceException in GetUboDeclarationById

### ISSUE THREAD

**Issue by xps** [Mangopay/mangopay2-net-sdk#86]
I am getting a null reference exception in:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at MangoPay.SDK.Core.RestTool.DoRequest[U,T](String idempotencyKey, String urlMethod, Pagination pagination, T entity)
   at MangoPay.SDK.Core.RestTool.Request[U,T](ApiEndPoint endPoint)
```

When calling:

```
mangoPayClient.UboDeclarations.GetUboDeclarationById(userId, uboDeclarationId)
```

In production with version 1.4.1 of the mangopay2-sdk NuGet package, but not when trying to reproduce the issue with the source code from the master branch.

Both parameters passed to `GetUboDeclarationById` are not null.

Was this fixed in a recent commit and if so, when will it land on NuGet?

Thank you

**Comment by SoloJr** [comment]
@xps I'm pretty sure that this was fixed. There is a test that covers this, and no exception gets thrown. I don't know when the release will be, but we're working on it :).
Maybe @mickaelpois can tell you when we'll release.
